# Generated by Django 4.2.25 on 2025-11-02 17:20

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('execution_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='집행ID')),
                ('department', models.CharField(max_length=100, verbose_name='소속학과')),
                ('total_budget', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='총연구비')),
                ('execution_date', models.DateField(verbose_name='집행일자')),
                ('execution_amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='집행금액')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Project',
                'verbose_name_plural': 'Research Projects',
                'db_table': 'research_projects',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='학번')),
                ('department', models.CharField(max_length=100, verbose_name='학과')),
                ('grade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='학년')),
                ('program_type', models.CharField(choices=[('학사', '학사'), ('석사', '석사'), ('박사', '박사')], max_length=20, verbose_name='과정구분')),
                ('enrollment_status', models.CharField(choices=[('재학', '재학'), ('휴학', '휴학'), ('졸업', '졸업')], max_length=20, verbose_name='학적상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='논문ID')),
                ('department', models.CharField(max_length=100, verbose_name='학과')),
                ('journal_tier', models.CharField(choices=[('SCIE', 'SCIE'), ('KCI', 'KCI'), ('기타', '기타')], max_length=20, verbose_name='저널등급')),
                ('impact_factor', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Impact Factor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'db_table': 'publications',
            },
        ),
        migrations.CreateModel(
            name='DepartmentKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)], verbose_name='평가년도')),
                ('department', models.CharField(max_length=100, verbose_name='학과')),
                ('employment_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='졸업생 취업률(%)')),
                ('tech_transfer_revenue', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='연간 기술이전 수입액(억원)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department KPI',
                'verbose_name_plural': 'Department KPIs',
                'db_table': 'department_kpis',
            },
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['department'], name='idx_rp_dept'),
        ),
        migrations.AddIndex(
            model_name='researchproject',
            index=models.Index(fields=['execution_date'], name='idx_rp_date'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='idx_student_dept'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['department'], name='idx_pub_dept'),
        ),
        migrations.AddIndex(
            model_name='departmentkpi',
            index=models.Index(fields=['evaluation_year'], name='idx_kpi_year'),
        ),
        migrations.AddIndex(
            model_name='departmentkpi',
            index=models.Index(fields=['department'], name='idx_kpi_dept'),
        ),
        migrations.AddConstraint(
            model_name='departmentkpi',
            constraint=models.UniqueConstraint(fields=('evaluation_year', 'department'), name='unique_year_department_kpi'),
        ),
    ]
