# Generated by Django 4.2.25 on 2025-11-02 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
                verbose_name="학년",
            ),
        ),
    ]
